/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CRC8_H
#define _MOCK_CRC8_H

#include "unity.h"
#include "Crc8.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Crc8_Init(void);
void mock_Crc8_Destroy(void);
void mock_Crc8_Verify(void);




#define Crc8_Calc_u8_Ignore() TEST_FAIL_MESSAGE("Crc8_Calc_u8 requires _IgnoreAndReturn");
#define Crc8_Calc_u8_IgnoreAndReturn(cmock_retval) Crc8_Calc_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Crc8_Calc_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Crc8_Calc_u8_StopIgnore() Crc8_Calc_u8_CMockStopIgnore()
void Crc8_Calc_u8_CMockStopIgnore(void);
#define Crc8_Calc_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("Crc8_Calc_u8 requires _ExpectAnyArgsAndReturn");
#define Crc8_Calc_u8_ExpectAnyArgsAndReturn(cmock_retval) Crc8_Calc_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Crc8_Calc_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Crc8_Calc_u8_Expect(dataPtr, dataLen) TEST_FAIL_MESSAGE("Crc8_Calc_u8 requires _ExpectAndReturn");
#define Crc8_Calc_u8_ExpectAndReturn(dataPtr, dataLen, cmock_retval) Crc8_Calc_u8_CMockExpectAndReturn(__LINE__, dataPtr, dataLen, cmock_retval)
void Crc8_Calc_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* dataPtr, size_t dataLen, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Crc8_Calc_u8_CALLBACK)(const uint8_t* dataPtr, size_t dataLen, int cmock_num_calls);
void Crc8_Calc_u8_AddCallback(CMOCK_Crc8_Calc_u8_CALLBACK Callback);
void Crc8_Calc_u8_Stub(CMOCK_Crc8_Calc_u8_CALLBACK Callback);
#define Crc8_Calc_u8_StubWithCallback Crc8_Calc_u8_Stub
#define Crc8_Calc_u8_ExpectWithArray(dataPtr, dataPtr_Depth, dataLen) TEST_FAIL_MESSAGE("Crc8_Calc_u8 requires _ExpectWithArrayAndReturn");
#define Crc8_Calc_u8_ExpectWithArrayAndReturn(dataPtr, dataPtr_Depth, dataLen, cmock_retval) Crc8_Calc_u8_CMockExpectWithArrayAndReturn(__LINE__, dataPtr, (dataPtr_Depth), dataLen, cmock_retval)
void Crc8_Calc_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* dataPtr, int dataPtr_Depth, size_t dataLen, uint8_t cmock_to_return);
#define Crc8_Calc_u8_IgnoreArg_dataPtr() Crc8_Calc_u8_CMockIgnoreArg_dataPtr(__LINE__)
void Crc8_Calc_u8_CMockIgnoreArg_dataPtr(UNITY_LINE_TYPE cmock_line);
#define Crc8_Calc_u8_IgnoreArg_dataLen() Crc8_Calc_u8_CMockIgnoreArg_dataLen(__LINE__)
void Crc8_Calc_u8_CMockIgnoreArg_dataLen(UNITY_LINE_TYPE cmock_line);
#define Crc8_Upd_u8_Ignore() TEST_FAIL_MESSAGE("Crc8_Upd_u8 requires _IgnoreAndReturn");
#define Crc8_Upd_u8_IgnoreAndReturn(cmock_retval) Crc8_Upd_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Crc8_Upd_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Crc8_Upd_u8_StopIgnore() Crc8_Upd_u8_CMockStopIgnore()
void Crc8_Upd_u8_CMockStopIgnore(void);
#define Crc8_Upd_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("Crc8_Upd_u8 requires _ExpectAnyArgsAndReturn");
#define Crc8_Upd_u8_ExpectAnyArgsAndReturn(cmock_retval) Crc8_Upd_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Crc8_Upd_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Crc8_Upd_u8_Expect(crc, dataByte) TEST_FAIL_MESSAGE("Crc8_Upd_u8 requires _ExpectAndReturn");
#define Crc8_Upd_u8_ExpectAndReturn(crc, dataByte, cmock_retval) Crc8_Upd_u8_CMockExpectAndReturn(__LINE__, crc, dataByte, cmock_retval)
void Crc8_Upd_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t crc, uint8_t dataByte, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Crc8_Upd_u8_CALLBACK)(uint8_t crc, uint8_t dataByte, int cmock_num_calls);
void Crc8_Upd_u8_AddCallback(CMOCK_Crc8_Upd_u8_CALLBACK Callback);
void Crc8_Upd_u8_Stub(CMOCK_Crc8_Upd_u8_CALLBACK Callback);
#define Crc8_Upd_u8_StubWithCallback Crc8_Upd_u8_Stub
#define Crc8_Upd_u8_IgnoreArg_crc() Crc8_Upd_u8_CMockIgnoreArg_crc(__LINE__)
void Crc8_Upd_u8_CMockIgnoreArg_crc(UNITY_LINE_TYPE cmock_line);
#define Crc8_Upd_u8_IgnoreArg_dataByte() Crc8_Upd_u8_CMockIgnoreArg_dataByte(__LINE__)
void Crc8_Upd_u8_CMockIgnoreArg_dataByte(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
