/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Crc8.h"

static const char* CMockString_Crc8_Calc_u8 = "Crc8_Calc_u8";
static const char* CMockString_Crc8_Upd_u8 = "Crc8_Upd_u8";
static const char* CMockString_crc = "crc";
static const char* CMockString_dataByte = "dataByte";
static const char* CMockString_dataLen = "dataLen";
static const char* CMockString_dataPtr = "dataPtr";

typedef struct _CMOCK_Crc8_Calc_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  const uint8_t* Expected_dataPtr;
  size_t Expected_dataLen;
  int Expected_dataPtr_Depth;
  char IgnoreArg_dataPtr;
  char IgnoreArg_dataLen;

} CMOCK_Crc8_Calc_u8_CALL_INSTANCE;

typedef struct _CMOCK_Crc8_Upd_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint8_t Expected_crc;
  uint8_t Expected_dataByte;
  char IgnoreArg_crc;
  char IgnoreArg_dataByte;

} CMOCK_Crc8_Upd_u8_CALL_INSTANCE;

static struct mock_Crc8Instance
{
  char Crc8_Calc_u8_IgnoreBool;
  uint8_t Crc8_Calc_u8_FinalReturn;
  char Crc8_Calc_u8_CallbackBool;
  CMOCK_Crc8_Calc_u8_CALLBACK Crc8_Calc_u8_CallbackFunctionPointer;
  int Crc8_Calc_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Crc8_Calc_u8_CallInstance;
  char Crc8_Upd_u8_IgnoreBool;
  uint8_t Crc8_Upd_u8_FinalReturn;
  char Crc8_Upd_u8_CallbackBool;
  CMOCK_Crc8_Upd_u8_CALLBACK Crc8_Upd_u8_CallbackFunctionPointer;
  int Crc8_Upd_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Crc8_Upd_u8_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Crc8_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Crc8_Calc_u8_CallInstance;
  if (Mock.Crc8_Calc_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Crc8_Calc_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Crc8_Calc_u8_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Crc8_Upd_u8_CallInstance;
  if (Mock.Crc8_Upd_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Crc8_Upd_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Crc8_Upd_u8_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Crc8_Init(void)
{
  mock_Crc8_Destroy();
}

void mock_Crc8_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

uint8_t Crc8_Calc_u8(const uint8_t* dataPtr, size_t dataLen)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Crc8_Calc_u8);
  cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Crc8_Calc_u8_CallInstance);
  Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemNext(Mock.Crc8_Calc_u8_CallInstance);
  if (Mock.Crc8_Calc_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Crc8_Calc_u8_FinalReturn;
    Mock.Crc8_Calc_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Crc8_Calc_u8_CallbackBool &&
      Mock.Crc8_Calc_u8_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.Crc8_Calc_u8_CallbackFunctionPointer(dataPtr, dataLen, Mock.Crc8_Calc_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_dataPtr)
  {
    UNITY_SET_DETAILS(CMockString_Crc8_Calc_u8,CMockString_dataPtr);
    if (cmock_call_instance->Expected_dataPtr == NULL)
      { UNITY_TEST_ASSERT_NULL(dataPtr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_dataPtr, dataPtr, cmock_call_instance->Expected_dataPtr_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_dataLen)
  {
    UNITY_SET_DETAILS(CMockString_Crc8_Calc_u8,CMockString_dataLen);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dataLen), (void*)(&dataLen), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Crc8_Calc_u8_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Crc8_Calc_u8_CallbackFunctionPointer(dataPtr, dataLen, Mock.Crc8_Calc_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Crc8_Calc_u8(CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance, const uint8_t* dataPtr, int dataPtr_Depth, size_t dataLen);
void CMockExpectParameters_Crc8_Calc_u8(CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance, const uint8_t* dataPtr, int dataPtr_Depth, size_t dataLen)
{
  cmock_call_instance->Expected_dataPtr = dataPtr;
  cmock_call_instance->Expected_dataPtr_Depth = dataPtr_Depth;
  cmock_call_instance->IgnoreArg_dataPtr = 0;
  memcpy((void*)(&cmock_call_instance->Expected_dataLen), (void*)(&dataLen),
         sizeof(size_t[sizeof(dataLen) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dataLen = 0;
}

void Crc8_Calc_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Calc_u8_CALL_INSTANCE));
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Calc_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Crc8_Calc_u8_IgnoreBool = (char)1;
}

void Crc8_Calc_u8_CMockStopIgnore(void)
{
  if(Mock.Crc8_Calc_u8_IgnoreBool)
    Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemNext(Mock.Crc8_Calc_u8_CallInstance);
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
}

void Crc8_Calc_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Calc_u8_CALL_INSTANCE));
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Calc_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Crc8_Calc_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* dataPtr, size_t dataLen, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Calc_u8_CALL_INSTANCE));
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Calc_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Crc8_Calc_u8(cmock_call_instance, dataPtr, 1, dataLen);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Crc8_Calc_u8_AddCallback(CMOCK_Crc8_Calc_u8_CALLBACK Callback)
{
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  Mock.Crc8_Calc_u8_CallbackBool = (char)1;
  Mock.Crc8_Calc_u8_CallbackFunctionPointer = Callback;
}

void Crc8_Calc_u8_Stub(CMOCK_Crc8_Calc_u8_CALLBACK Callback)
{
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  Mock.Crc8_Calc_u8_CallbackBool = (char)0;
  Mock.Crc8_Calc_u8_CallbackFunctionPointer = Callback;
}

void Crc8_Calc_u8_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* dataPtr, int dataPtr_Depth, size_t dataLen, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Calc_u8_CALL_INSTANCE));
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Calc_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Calc_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Calc_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Crc8_Calc_u8(cmock_call_instance, dataPtr, dataPtr_Depth, dataLen);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Crc8_Calc_u8_CMockIgnoreArg_dataPtr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Crc8_Calc_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dataPtr = 1;
}

void Crc8_Calc_u8_CMockIgnoreArg_dataLen(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Crc8_Calc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Calc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Crc8_Calc_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dataLen = 1;
}

uint8_t Crc8_Upd_u8(uint8_t crc, uint8_t dataByte)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Crc8_Upd_u8);
  cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Crc8_Upd_u8_CallInstance);
  Mock.Crc8_Upd_u8_CallInstance = CMock_Guts_MemNext(Mock.Crc8_Upd_u8_CallInstance);
  if (Mock.Crc8_Upd_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Crc8_Upd_u8_FinalReturn;
    Mock.Crc8_Upd_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Crc8_Upd_u8_CallbackBool &&
      Mock.Crc8_Upd_u8_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.Crc8_Upd_u8_CallbackFunctionPointer(crc, dataByte, Mock.Crc8_Upd_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_crc)
  {
    UNITY_SET_DETAILS(CMockString_Crc8_Upd_u8,CMockString_crc);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_crc, crc, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dataByte)
  {
    UNITY_SET_DETAILS(CMockString_Crc8_Upd_u8,CMockString_dataByte);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_dataByte, dataByte, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Crc8_Upd_u8_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Crc8_Upd_u8_CallbackFunctionPointer(crc, dataByte, Mock.Crc8_Upd_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Crc8_Upd_u8(CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance, uint8_t crc, uint8_t dataByte);
void CMockExpectParameters_Crc8_Upd_u8(CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance, uint8_t crc, uint8_t dataByte)
{
  cmock_call_instance->Expected_crc = crc;
  cmock_call_instance->IgnoreArg_crc = 0;
  cmock_call_instance->Expected_dataByte = dataByte;
  cmock_call_instance->IgnoreArg_dataByte = 0;
}

void Crc8_Upd_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Upd_u8_CALL_INSTANCE));
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Upd_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Upd_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Crc8_Upd_u8_IgnoreBool = (char)1;
}

void Crc8_Upd_u8_CMockStopIgnore(void)
{
  if(Mock.Crc8_Upd_u8_IgnoreBool)
    Mock.Crc8_Upd_u8_CallInstance = CMock_Guts_MemNext(Mock.Crc8_Upd_u8_CallInstance);
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
}

void Crc8_Upd_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Upd_u8_CALL_INSTANCE));
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Upd_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Upd_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Crc8_Upd_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t crc, uint8_t dataByte, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Crc8_Upd_u8_CALL_INSTANCE));
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Crc8_Upd_u8_CallInstance = CMock_Guts_MemChain(Mock.Crc8_Upd_u8_CallInstance, cmock_guts_index);
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Crc8_Upd_u8(cmock_call_instance, crc, dataByte);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Crc8_Upd_u8_AddCallback(CMOCK_Crc8_Upd_u8_CALLBACK Callback)
{
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
  Mock.Crc8_Upd_u8_CallbackBool = (char)1;
  Mock.Crc8_Upd_u8_CallbackFunctionPointer = Callback;
}

void Crc8_Upd_u8_Stub(CMOCK_Crc8_Upd_u8_CALLBACK Callback)
{
  Mock.Crc8_Upd_u8_IgnoreBool = (char)0;
  Mock.Crc8_Upd_u8_CallbackBool = (char)0;
  Mock.Crc8_Upd_u8_CallbackFunctionPointer = Callback;
}

void Crc8_Upd_u8_CMockIgnoreArg_crc(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Crc8_Upd_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_crc = 1;
}

void Crc8_Upd_u8_CMockIgnoreArg_dataByte(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Crc8_Upd_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_Crc8_Upd_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Crc8_Upd_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dataByte = 1;
}

