/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Crc8_priv.h"

static const char* CMockString_BuildTbl = "BuildTbl";
static const char* CMockString_EnsureTblInit = "EnsureTblInit";

typedef struct _CMOCK_EnsureTblInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_EnsureTblInit_CALL_INSTANCE;

typedef struct _CMOCK_BuildTbl_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_BuildTbl_CALL_INSTANCE;

static struct mock_Crc8_privInstance
{
  char EnsureTblInit_IgnoreBool;
  char EnsureTblInit_CallbackBool;
  CMOCK_EnsureTblInit_CALLBACK EnsureTblInit_CallbackFunctionPointer;
  int EnsureTblInit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE EnsureTblInit_CallInstance;
  char BuildTbl_IgnoreBool;
  char BuildTbl_CallbackBool;
  CMOCK_BuildTbl_CALLBACK BuildTbl_CallbackFunctionPointer;
  int BuildTbl_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BuildTbl_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Crc8_priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.EnsureTblInit_CallInstance;
  if (Mock.EnsureTblInit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_EnsureTblInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.EnsureTblInit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BuildTbl_CallInstance;
  if (Mock.BuildTbl_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BuildTbl);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BuildTbl_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Crc8_priv_Init(void)
{
  mock_Crc8_priv_Destroy();
}

void mock_Crc8_priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void EnsureTblInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EnsureTblInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_EnsureTblInit);
  cmock_call_instance = (CMOCK_EnsureTblInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EnsureTblInit_CallInstance);
  Mock.EnsureTblInit_CallInstance = CMock_Guts_MemNext(Mock.EnsureTblInit_CallInstance);
  if (Mock.EnsureTblInit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.EnsureTblInit_CallbackBool &&
      Mock.EnsureTblInit_CallbackFunctionPointer != NULL)
  {
    Mock.EnsureTblInit_CallbackFunctionPointer(Mock.EnsureTblInit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.EnsureTblInit_CallbackFunctionPointer != NULL)
  {
    Mock.EnsureTblInit_CallbackFunctionPointer(Mock.EnsureTblInit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void EnsureTblInit_CMockIgnore(void)
{
  Mock.EnsureTblInit_IgnoreBool = (char)1;
}

void EnsureTblInit_CMockStopIgnore(void)
{
  Mock.EnsureTblInit_IgnoreBool = (char)0;
}

void EnsureTblInit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EnsureTblInit_CALL_INSTANCE));
  CMOCK_EnsureTblInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_EnsureTblInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.EnsureTblInit_CallInstance = CMock_Guts_MemChain(Mock.EnsureTblInit_CallInstance, cmock_guts_index);
  Mock.EnsureTblInit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void EnsureTblInit_AddCallback(CMOCK_EnsureTblInit_CALLBACK Callback)
{
  Mock.EnsureTblInit_IgnoreBool = (char)0;
  Mock.EnsureTblInit_CallbackBool = (char)1;
  Mock.EnsureTblInit_CallbackFunctionPointer = Callback;
}

void EnsureTblInit_Stub(CMOCK_EnsureTblInit_CALLBACK Callback)
{
  Mock.EnsureTblInit_IgnoreBool = (char)0;
  Mock.EnsureTblInit_CallbackBool = (char)0;
  Mock.EnsureTblInit_CallbackFunctionPointer = Callback;
}

void BuildTbl(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BuildTbl_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BuildTbl);
  cmock_call_instance = (CMOCK_BuildTbl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BuildTbl_CallInstance);
  Mock.BuildTbl_CallInstance = CMock_Guts_MemNext(Mock.BuildTbl_CallInstance);
  if (Mock.BuildTbl_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.BuildTbl_CallbackBool &&
      Mock.BuildTbl_CallbackFunctionPointer != NULL)
  {
    Mock.BuildTbl_CallbackFunctionPointer(Mock.BuildTbl_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.BuildTbl_CallbackFunctionPointer != NULL)
  {
    Mock.BuildTbl_CallbackFunctionPointer(Mock.BuildTbl_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void BuildTbl_CMockIgnore(void)
{
  Mock.BuildTbl_IgnoreBool = (char)1;
}

void BuildTbl_CMockStopIgnore(void)
{
  Mock.BuildTbl_IgnoreBool = (char)0;
}

void BuildTbl_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BuildTbl_CALL_INSTANCE));
  CMOCK_BuildTbl_CALL_INSTANCE* cmock_call_instance = (CMOCK_BuildTbl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BuildTbl_CallInstance = CMock_Guts_MemChain(Mock.BuildTbl_CallInstance, cmock_guts_index);
  Mock.BuildTbl_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void BuildTbl_AddCallback(CMOCK_BuildTbl_CALLBACK Callback)
{
  Mock.BuildTbl_IgnoreBool = (char)0;
  Mock.BuildTbl_CallbackBool = (char)1;
  Mock.BuildTbl_CallbackFunctionPointer = Callback;
}

void BuildTbl_Stub(CMOCK_BuildTbl_CALLBACK Callback)
{
  Mock.BuildTbl_IgnoreBool = (char)0;
  Mock.BuildTbl_CallbackBool = (char)0;
  Mock.BuildTbl_CallbackFunctionPointer = Callback;
}

