/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CRC8_PRIV_H
#define _MOCK_CRC8_PRIV_H

#include "unity.h"
#include "Crc8_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Crc8_priv_Init(void);
void mock_Crc8_priv_Destroy(void);
void mock_Crc8_priv_Verify(void);




#define EnsureTblInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("EnsureTblInit requires _Ignore (not AndReturn)");
#define EnsureTblInit_Ignore() EnsureTblInit_CMockIgnore()
void EnsureTblInit_CMockIgnore(void);
#define EnsureTblInit_StopIgnore() EnsureTblInit_CMockStopIgnore()
void EnsureTblInit_CMockStopIgnore(void);
#define EnsureTblInit_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("EnsureTblInit requires _Expect (not AndReturn)");
#define EnsureTblInit_Expect() EnsureTblInit_CMockExpect(__LINE__)
void EnsureTblInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_EnsureTblInit_CALLBACK)(int cmock_num_calls);
void EnsureTblInit_AddCallback(CMOCK_EnsureTblInit_CALLBACK Callback);
void EnsureTblInit_Stub(CMOCK_EnsureTblInit_CALLBACK Callback);
#define EnsureTblInit_StubWithCallback EnsureTblInit_Stub
#define CalcByte_u8_Ignore() TEST_FAIL_MESSAGE("CalcByte_u8 requires _IgnoreAndReturn");
#define CalcByte_u8_IgnoreAndReturn(cmock_retval) CalcByte_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CalcByte_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define CalcByte_u8_StopIgnore() CalcByte_u8_CMockStopIgnore()
void CalcByte_u8_CMockStopIgnore(void);
#define CalcByte_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("CalcByte_u8 requires _ExpectAnyArgsAndReturn");
#define CalcByte_u8_ExpectAnyArgsAndReturn(cmock_retval) CalcByte_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void CalcByte_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define CalcByte_u8_Expect(crc, dataByte) TEST_FAIL_MESSAGE("CalcByte_u8 requires _ExpectAndReturn");
#define CalcByte_u8_ExpectAndReturn(crc, dataByte, cmock_retval) CalcByte_u8_CMockExpectAndReturn(__LINE__, crc, dataByte, cmock_retval)
void CalcByte_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t crc, uint8_t dataByte, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_CalcByte_u8_CALLBACK)(uint8_t crc, uint8_t dataByte, int cmock_num_calls);
void CalcByte_u8_AddCallback(CMOCK_CalcByte_u8_CALLBACK Callback);
void CalcByte_u8_Stub(CMOCK_CalcByte_u8_CALLBACK Callback);
#define CalcByte_u8_StubWithCallback CalcByte_u8_Stub
#define CalcByte_u8_IgnoreArg_crc() CalcByte_u8_CMockIgnoreArg_crc(__LINE__)
void CalcByte_u8_CMockIgnoreArg_crc(UNITY_LINE_TYPE cmock_line);
#define CalcByte_u8_IgnoreArg_dataByte() CalcByte_u8_CMockIgnoreArg_dataByte(__LINE__)
void CalcByte_u8_CMockIgnoreArg_dataByte(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
