/******************************************************************************/
/* Crc8_priv.h                                                                */
/******************************************************************************/
#ifndef CRC8_PRIV_H
#define CRC8_PRIV_H

#include <stdbool.h>
#include <stdint.h>

/**
 * @file Crc8_priv.h
 * @brief Private interface for CRC-8 implementation (lookup-table based).
 *
 * @details
 * This header declares private, translation-unit-local symbols used exclusively
 * by `Crc8.c`:
 * - `Crc8Tbl_u8[256]`: CRC-8 lookup table
 * - `Crc8TblInitFlg_b`: one-time init flag
 * - `EnsureTblInit()`: lazy initialization gate
 * - `BuildTbl()`: runtime generation of the lookup table
 * - `CalcByte_u8()`: table-driven CRC update for a single byte
 *
 * @note Intended usage:
 * - Include this header **only** in `Crc8.c`.
 * - All declarations are `static` so they remain local to the translation unit.
 *
 * @par Design notes
 * The table is built once on demand to avoid startup overhead when CRC is not used.
 * The update rule is table-driven:
 * `crc' = table[crc XOR dataByte]`
 *
 * @par Reentrancy / thread-safety
 * The functions operate on static state (table + init flag). If multiple threads
 * might call CRC APIs simultaneously for the first time, protect the first-time
 * initialization (or provide a dedicated init call executed single-threaded).
 */

/* Private (cfile-static) variables (Table 6: Global static -> N/A + PascalCasing + _datatype) */

/**
 * @brief CRC-8 lookup table (256 entries).
 *
 * @details
 * The table stores the precomputed CRC-8 transform for all possible 8-bit indices.
 * It is generated by @ref BuildTbl and later used by @ref CalcByte_u8 to update
 * the CRC in O(1) per processed byte.
 */
static uint8_t Crc8Tbl_u8[256u];

/**
 * @brief CRC-8 lookup table initialization flag.
 *
 * @details
 * Indicates whether @ref Crc8Tbl_u8 has already been generated.
 * - `false`: table not initialized yet
 * - `true`:  table ready to use
 */
static bool Crc8TblInitFlg_b;

/* Private (cfile-static) functions (Table 7: Local -> no prefix + PascalCasing) */

/**
 * @brief Ensure the CRC-8 lookup table is initialized.
 *
 * @details
 * **Goal of the function**
 *
 * Guarantee that the lookup table is built exactly once before use.
 *
 * The processing logic:
 * - If `Crc8TblInitFlg_b` is `false`, call @ref BuildTbl.
 * - Set `Crc8TblInitFlg_b` to `true`.
 *
 * @par Interface summary
 *
 * | Interface            | In | Out | Data type / Signature | Param | Data factor | Data offset | Data size | Data range | Data unit |
 * |----------------------|:--:|:---:|------------------------|:-----:|------------:|------------:|----------:|-----------:|----------|
 * | Crc8TblInitFlg_b     | X  |  X  | bool                   |   -   |      1      |      0      |     1     | {0,1}      | [-]      |
 * | BuildTbl()           | X  |  X  | void(void)             |   -   |      -      |      -      |     -     | -          | [-]      |
 *
 * @par Activity diagram (PlantUML)
 *
 * @startuml
 * start
 * if (Crc8TblInitFlg_b == false) then (yes)
 *   :BuildTbl();
 *   :Crc8TblInitFlg_b = true;
 * endif
 * stop
 * @enduml
 *
 * @return None.
 */
static void EnsureTblInit(void);

/**
 * @brief Build the CRC-8 lookup table.
 *
 * @details
 * **Goal of the function**
 *
 * Precompute CRC-8 results for all 256 possible byte values, according to the
 * configured polynomial (`CRC8_POLY_U8`), and store them in @ref Crc8Tbl_u8.
 *
 * The processing logic:
 * - For each `idx` in [0..255]:
 *   - Set `crc = (uint8_t)idx`
 *   - Repeat 8 times:
 *     - If MSB of `crc` is set, shift left and XOR with `CRC8_POLY_U8`
 *     - Else shift left
 *   - Store `crc` into `Crc8Tbl_u8[idx]`
 *
 * @par Interface summary
 *
 * | Interface          | In | Out | Data type / Signature           | Param | Data factor | Data offset | Data size | Data range | Data unit |
 * |--------------------|:--:|:---:|---------------------------------|:-----:|------------:|------------:|----------:|-----------:|----------|
 * | Crc8Tbl_u8[idx]    |    |  X  | uint8_t[256]                      |   -   |      1      |      0      |    256    | [0,255]    | [-]      |
 * | CRC8_POLY_U8       | X  |     | uint8_t (constant / macro)        |   -   |      -      |      -      |     -     | [0,255]    | [-]      |
 *
 * @par Activity diagram (PlantUML)
 *
 * @startuml
 * start
 * :idx = 0;
 * while (idx < 256) is (yes)
 *   :crc = (uint8_t)idx;
 *   :bitIdx = 0;
 *   while (bitIdx < 8) is (yes)
 *     if ((crc & 0x80) != 0) then (msb=1)
 *       :crc = (crc << 1) XOR CRC8_POLY_U8;
 *     else (msb=0)
 *       :crc = crc << 1;
 *     endif
 *     :bitIdx++;
 *   endwhile (no)
 *   :Crc8Tbl_u8[idx] = crc;
 *   :idx++;
 * endwhile (no)
 * stop
 * @enduml
 *
 * @return None.
 */
static void BuildTbl(void);

/**
 * @brief Update CRC-8 using the lookup table for a single input byte.
 *
 * @details
 * **Goal of the function**
 *
 * Compute the next CRC-8 value from the current CRC and one byte using the
 * precomputed lookup table.
 *
 * The processing logic:
 * - Index = `(uint8_t)(crc ^ dataByte)`
 * - Return `Crc8Tbl_u8[Index]`
 *
 * @par Interface summary
 *
 * | Interface         | In | Out | Data type / Signature                    | Param | Data factor | Data offset | Data size | Data range | Data unit |
 * |-------------------|:--:|:---:|------------------------------------------|:-----:|------------:|------------:|----------:|-----------:|----------|
 * | crc               | X  |     | uint8_t                                    |   X   |      1      |      0      |     1     | [0,255]    | [-]      |
 * | dataByte          | X  |     | uint8_t                                    |   X   |      1      |      0      |     1     | [0,255]    | [-]      |
 * | Crc8Tbl_u8[]      | X  |     | uint8_t[256]                               |   -   |      1      |      0      |    256    | [0,255]    | [-]      |
 *
 * @par Activity diagram (PlantUML)
 *
 * @startuml
 * start
 * :idx = (uint8_t)(crc XOR dataByte);
 * :crcNew = Crc8Tbl_u8[idx];
 * :return crcNew;
 * stop
 * @enduml
 *
 * @param crc
 * Current CRC-8 value.
 *
 * @param dataByte
 * Next input byte to process.
 *
 * @return Updated CRC-8 value after processing @p dataByte.
 *
 * @warning
 * The lookup table must be initialized before calling this function.
 * Typically ensured by calling @ref EnsureTblInit from the public APIs.
 */
static uint8_t CalcByte_u8(uint8_t crc, uint8_t dataByte);

#endif /* CRC8_PRIV_H */
