/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CRC8_PRIV_H
#define _MOCK_CRC8_PRIV_H

#include "unity.h"
#include "Crc8_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Crc8_priv_Init(void);
void mock_Crc8_priv_Destroy(void);
void mock_Crc8_priv_Verify(void);




#define EnsureTblInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("EnsureTblInit requires _Ignore (not AndReturn)");
#define EnsureTblInit_Ignore() EnsureTblInit_CMockIgnore()
void EnsureTblInit_CMockIgnore(void);
#define EnsureTblInit_StopIgnore() EnsureTblInit_CMockStopIgnore()
void EnsureTblInit_CMockStopIgnore(void);
#define EnsureTblInit_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("EnsureTblInit requires _Expect (not AndReturn)");
#define EnsureTblInit_Expect() EnsureTblInit_CMockExpect(__LINE__)
void EnsureTblInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_EnsureTblInit_CALLBACK)(int cmock_num_calls);
void EnsureTblInit_AddCallback(CMOCK_EnsureTblInit_CALLBACK Callback);
void EnsureTblInit_Stub(CMOCK_EnsureTblInit_CALLBACK Callback);
#define EnsureTblInit_StubWithCallback EnsureTblInit_Stub
#define BuildTbl_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("BuildTbl requires _Ignore (not AndReturn)");
#define BuildTbl_Ignore() BuildTbl_CMockIgnore()
void BuildTbl_CMockIgnore(void);
#define BuildTbl_StopIgnore() BuildTbl_CMockStopIgnore()
void BuildTbl_CMockStopIgnore(void);
#define BuildTbl_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("BuildTbl requires _Expect (not AndReturn)");
#define BuildTbl_Expect() BuildTbl_CMockExpect(__LINE__)
void BuildTbl_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_BuildTbl_CALLBACK)(int cmock_num_calls);
void BuildTbl_AddCallback(CMOCK_BuildTbl_CALLBACK Callback);
void BuildTbl_Stub(CMOCK_BuildTbl_CALLBACK Callback);
#define BuildTbl_StubWithCallback BuildTbl_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
